### ISSUE TITLE
I get error when -66.1188918 longitude is negative

### ISSUE THREAD

**Issue by cjlaborde** [akuechler/laravel-geoly#3]
Illuminate\Database\QueryException
SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at end of input LINE 1: ...itude))*cos(radians(longitude)-?)) * ? < ? order by distance ^ (SQL: select *, acos(sin(0.3222817973143)*sin(radians(latitude)) + cos(0.3222817973143)*cos(radians(latitude))*cos(radians(longitude)--1.1539923596799)) * 6371 As distance from (select * from "rooms" where "latitude" between 18.375454639408 and 18.555318960592 and "longitude" between -66.213705462789 and -66.024078137211) as "rooms" where acos(sin(0.3222817973143)*sin(radians(latitude)) + cos(0.3222817973143)*cos(radians(latitude))*cos(radians(longitude)--1.1539923596799)) * 6371 < 10 order by distance)

**Comment by axkuechler** [comment]
Thank you for reporting this issue. Will fix it within the next days.

**Comment by cjlaborde** [comment]
Sure let me know if you need more data.
Here is the 2 locations I was trying to use with this code.
1) longitude  -66.1160422 latitude 18.4682047
2) longitude -66.1188918 latitude 18.4653868

**Comment by FelipeSamuel** [comment]
Any fixes for this problem?

**Comment by axkuechler** [comment]
Fixed with the current release v1.0.5. Sorry for the delay. Should work now like expected.
