### ISSUE TITLE
Numeric value out of range with Postgres 12

### ISSUE THREAD

**Issue by smadrom** [akuechler/laravel-geoly#5]
Hi.

> SQLSTATE[22003]: Numeric value out of range: 7 ERROR:  input is out of range (SQL: select *, acos(sin(1.0395159958754)*sin(radians(latitude)) + cos(1.0395159958754)*cos(radians(latitude))*cos(radians(longitude)-0.52601709333789)) * 6371 As distance from (select * from "cities" where "latitude" between 57.761236088163 and 61.358522511837 and "longitude" between 26.587818705252 and 33.689300094748) as "cities" where acos(sin(1.0395159958754)*sin(radians(latitude)) + cos(1.0395159958754)*cos(radians(latitude))*cos(radians(longitude)-0.52601709333789)) * 6371 < 200 and "size" >= 2 order by distance, "size" desc limit 50

Latitude: 59.5598793
Longitude: 30.1385594

**Comment by axkuechler** [comment]
Hi, please share your migration for the relevant table.
